using HelperLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace TunoUI
{
    /// <summary>
    /// Interaction logic for NewOrderPage.xaml
    /// </summary>
    public partial class NewOrderPage : Page
    {
        public NewOrderPage()
        {
            InitializeComponent();
            BindComboBox(comboBoxBarNavn);
            BindCombobox2(comboBoxVareValg);
        }

        private List<BarModel> barnavne;
        public void BindComboBox(ComboBox comboBoxBarNavn)
        {
            barnavne = SQLiteDataAccess.GetBar();
            comboBoxBarNavn.ItemsSource = barnavne;
        }
        private List<ItemModel> varer;
        public void BindCombobox2(ComboBox comboBoxVareValg)
        {
            varer = SQLiteDataAccess.GetItem();
            comboBoxVareValg.ItemsSource = varer;
        }
        
        // I am not 100% sure here. I believe I have to create a List (maybe dynamic) that takes in each orderline and saves it temporarily until the full order is ready to be processed (saved to SQL)
        // The list should look like: Orderid, date, barname, itemname, itemquantity - the orderlineid is autogenerated in SQL.
    }
}
